name: Build Frontend and Test
on:
  push:
    branches: 
      - develop
      - feature/*
  pull_request:
    branches: 
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test